import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODELS_DIR = os.path.join(ROOT, "models")
AUDIO_MODEL_DIR = os.path.join(ROOT, "model")

# Camera settings copied from the Chani/JH branch and kept local to ultra_yubin_v1.
CAMERA_ID = os.getenv("CAMERA_ID", "auto")
CAMERA_WIDTH = int(os.getenv("CAMERA_WIDTH", "1280"))
CAMERA_HEIGHT = int(os.getenv("CAMERA_HEIGHT", "720"))
CAMERA_FPS = int(os.getenv("CAMERA_FPS", "60"))
CAMERA_FOURCC = os.getenv("CAMERA_FOURCC", "MJPG")
CAMERA_ROTATE_180 = os.getenv("CAMERA_ROTATE_180", "0") == "1"
CAMERA_FLIP_VERTICAL = os.getenv("CAMERA_FLIP_VERTICAL", "0") == "1"
CAMERA_FLIP_HORIZONTAL = os.getenv("CAMERA_FLIP_HORIZONTAL", "0") == "1"
CAMERA_CENTER_CROP = os.getenv("CAMERA_CENTER_CROP", "0") == "1"
CAMERA_CROP_SCALE = float(os.getenv("CAMERA_CROP_SCALE", "0.70"))
CAMERA_THREAD_SLEEP_SEC = float(os.getenv("CAMERA_THREAD_SLEEP_SEC", "0.001"))
CAMERA_APPLY_SETTINGS = os.getenv("CAMERA_APPLY_SETTINGS", "0") == "1"
CAMERA_AUTO_EXPOSURE = int(os.getenv("CAMERA_AUTO_EXPOSURE", "1"))
CAMERA_EXPOSURE = int(os.getenv("CAMERA_EXPOSURE", "43"))
CAMERA_GAIN = int(os.getenv("CAMERA_GAIN", "16"))
CAMERA_BRIGHTNESS = int(os.getenv("CAMERA_BRIGHTNESS", "0"))
CAMERA_CONTRAST = int(os.getenv("CAMERA_CONTRAST", "0"))
CAMERA_SATURATION = int(os.getenv("CAMERA_SATURATION", "64"))
CAMERA_SHARPNESS = int(os.getenv("CAMERA_SHARPNESS", "2"))
CAMERA_BACKLIGHT = int(os.getenv("CAMERA_BACKLIGHT", "0"))
CAMERA_GAMMA = int(os.getenv("CAMERA_GAMMA", "100"))
CAMERA_APPLY_GLARE_DEFAULTS = os.getenv("CAMERA_APPLY_GLARE_DEFAULTS", "0") == "1"
CAMERA_GLARE_EXPOSURE_STEP = int(os.getenv("CAMERA_GLARE_EXPOSURE_STEP", "10"))
CAMERA_GLARE_GAIN_STEP = int(os.getenv("CAMERA_GLARE_GAIN_STEP", "4"))
CAMERA_GLARE_EXPOSURE_MIN = int(os.getenv("CAMERA_GLARE_EXPOSURE_MIN", "3"))
CAMERA_GLARE_EXPOSURE_MAX = int(os.getenv("CAMERA_GLARE_EXPOSURE_MAX", "2047"))
CAMERA_GLARE_GAIN_MIN = int(os.getenv("CAMERA_GLARE_GAIN_MIN", "0"))
CAMERA_GLARE_GAIN_MAX = int(os.getenv("CAMERA_GLARE_GAIN_MAX", "255"))
CAMERA_GLARE_RESET_EXPOSURE = int(os.getenv("CAMERA_GLARE_RESET_EXPOSURE", "166"))
CAMERA_GLARE_RESET_GAIN = int(os.getenv("CAMERA_GLARE_RESET_GAIN", "32"))
CAMERA_GLARE_RESET_BACKLIGHT = int(os.getenv("CAMERA_GLARE_RESET_BACKLIGHT", "1"))

# Tello/drone YOLO model copied from /home/jetson/jh.
DRONE_ENGINE = os.path.join(MODELS_DIR, "drone_best_final_0520.engine")
DRONE_PT = os.path.join(MODELS_DIR, "drone_best_final_0520.pt")
if os.path.exists(DRONE_ENGINE):
    YOLO_MODEL_PATH = DRONE_ENGINE
elif os.path.exists(DRONE_PT):
    YOLO_MODEL_PATH = DRONE_PT
else:
    YOLO_MODEL_PATH = DRONE_ENGINE
YOLO_MODEL_PATH = os.getenv("YOLO_MODEL_PATH", YOLO_MODEL_PATH)
YOLO_MODEL = YOLO_MODEL_PATH
YOLO_DEVICE = os.getenv("YOLO_DEVICE", "cuda:0")
YOLO_CONF = float(os.getenv("YOLO_CONF", "0.70"))
YOLO_IMGSZ = int(os.getenv("YOLO_IMGSZ", "640"))
YOLO_SKIP_FRAMES = int(os.getenv("YOLO_SKIP_FRAMES", "1"))
YOLO_FAST_DETECT = os.getenv("YOLO_FAST_DETECT", "0") == "1"
AERIAL_TARGET_CLASSES = [0]

# jh HUD settings.
UI_RENDER_INTERVAL_FRAMES = int(os.getenv("UI_RENDER_INTERVAL_FRAMES", "2"))
UI_CAMERA_EVERY_FRAME = os.getenv("UI_CAMERA_EVERY_FRAME", "1") == "1"
UI_MINIMAL = os.getenv("UI_MINIMAL", "1") == "1"
UI_FULLSCREEN = os.getenv("UI_FULLSCREEN", "1") == "1"
UI_SCREEN_WIDTH = int(os.getenv("UI_SCREEN_WIDTH", "0"))
UI_SCREEN_HEIGHT = int(os.getenv("UI_SCREEN_HEIGHT", "0"))
UI_PANEL_WIDTH = int(os.getenv("UI_PANEL_WIDTH", "360"))
UI_CAMERA_FIT_MODE = os.getenv("UI_CAMERA_FIT_MODE", "stretch")
UI_FORCE_FULLSCREEN_FILL = os.getenv("UI_FORCE_FULLSCREEN_FILL", "0") == "1"
UI_FAST_DRAW = os.getenv("UI_FAST_DRAW", "0") == "1"
UI_SHOW_RETICLE = os.getenv("UI_SHOW_RETICLE", "1") == "1"
UI_RETICLE_FOLLOW_TARGET = os.getenv("UI_RETICLE_FOLLOW_TARGET", "0") == "1"
UI_SHOW_CAMERA_CENTER = os.getenv("UI_SHOW_CAMERA_CENTER", "1") == "1"
UI_SHOW_LASER_CENTER_MARKER = os.getenv("UI_SHOW_LASER_CENTER_MARKER", "0") == "1"
UI_LASER_CENTER_MARKER_STYLE = os.getenv("UI_LASER_CENTER_MARKER_STYLE", "full").strip().lower()
UI_SHOW_BBOX_LABEL = os.getenv("UI_SHOW_BBOX_LABEL", "1") == "1"
UI_SHOW_BBOX_CROSSHAIR = os.getenv("UI_SHOW_BBOX_CROSSHAIR", "1") == "1"
UI_AUDIO_HOLD_SEC = float(os.getenv("UI_AUDIO_HOLD_SEC", "5.0"))

# Tracking / state-machine parameters used by copied jh modules.
DETECT_CONFIRM_FRAMES = int(os.getenv("DETECT_CONFIRM_FRAMES", "4"))
LOCK_HOLD_SECONDS = float(os.getenv("LOCK_HOLD_SECONDS", "2.0"))
LOCK_AIM_THRESHOLD = float(os.getenv("LOCK_AIM_THRESHOLD", "80.0"))
NEUTRALIZED_HOLD_SEC = float(os.getenv("NEUTRALIZED_HOLD_SEC", "4.0"))
DRONE_LOST_RESET_SEC = float(os.getenv("DRONE_LOST_RESET_SEC", "7.0"))
TRACK_LOCK_SAME_OBJECT = os.getenv("TRACK_LOCK_SAME_OBJECT", "1") == "1"
TRACK_STICKY_MAX_DIST_PX = float(os.getenv("TRACK_STICKY_MAX_DIST_PX", "320"))
TRACK_PREFER_SAME_ID = os.getenv("TRACK_PREFER_SAME_ID", "0") == "1"
TRACK_SAME_ID_MAX_DIST_PX = float(os.getenv("TRACK_SAME_ID_MAX_DIST_PX", "320"))
TRACK_REACQUIRE_AFTER_ABSENT_FRAMES = int(os.getenv("TRACK_REACQUIRE_AFTER_ABSENT_FRAMES", "6"))
TRACK_REACQUIRE_MIN_CONF = float(os.getenv("TRACK_REACQUIRE_MIN_CONF", "0.70"))
TRACK_HOLD_LAST_FRAMES = int(os.getenv("TRACK_HOLD_LAST_FRAMES", "8"))
TRACK_HOLD_PREDICT_MAX_STEP_PX = float(os.getenv("TRACK_HOLD_PREDICT_MAX_STEP_PX", "12"))
TRACK_MOTOR_USE_HELD = os.getenv("TRACK_MOTOR_USE_HELD", "0") == "1"
TRACK_TARGET_MIN_CONF = float(os.getenv("TRACK_TARGET_MIN_CONF", "0.70"))
TRACK_TARGET_MIN_AREA = int(os.getenv("TRACK_TARGET_MIN_AREA", "120"))
TRACK_TARGET_MIN_W = int(os.getenv("TRACK_TARGET_MIN_W", "5"))
TRACK_TARGET_MIN_H = int(os.getenv("TRACK_TARGET_MIN_H", "4"))
TRACK_TARGET_MIN_ASPECT = float(os.getenv("TRACK_TARGET_MIN_ASPECT", "0.0"))
TRACK_TARGET_MAX_ASPECT = float(os.getenv("TRACK_TARGET_MAX_ASPECT", "10000.0"))
TRACK_WEAK_REACQUIRE_CONF = float(os.getenv("TRACK_WEAK_REACQUIRE_CONF", "0.70"))
TRACK_WEAK_REACQUIRE_AREA = int(os.getenv("TRACK_WEAK_REACQUIRE_AREA", "60"))
TRACK_WEAK_REACQUIRE_MAX_DIST_PX = float(os.getenv("TRACK_WEAK_REACQUIRE_MAX_DIST_PX", "320"))
TRACK_MOTOR_MIN_CONF = float(os.getenv("TRACK_MOTOR_MIN_CONF", "0.70"))
TRACK_MOTOR_MIN_AREA = int(os.getenv("TRACK_MOTOR_MIN_AREA", "80"))
TRACK_MOTOR_MIN_W = int(os.getenv("TRACK_MOTOR_MIN_W", "5"))
TRACK_MOTOR_MIN_H = int(os.getenv("TRACK_MOTOR_MIN_H", "4"))
TRACK_MOTOR_EDGE_MARGIN_X = int(os.getenv("TRACK_MOTOR_EDGE_MARGIN_X", "0"))
TRACK_MOTOR_EDGE_MARGIN_Y = int(os.getenv("TRACK_MOTOR_EDGE_MARGIN_Y", "0"))
TRACK_VISION_MOTOR_ENABLE = os.getenv("TRACK_VISION_MOTOR_ENABLE", "1") == "1"
TRACK_CENTER_LOCK_X_PX = int(os.getenv("TRACK_CENTER_LOCK_X_PX", "10"))
TRACK_CENTER_LOCK_Y_PX = int(os.getenv("TRACK_CENTER_LOCK_Y_PX", "10"))
TARGET_CENTER_SMOOTHING = float(os.getenv("TARGET_CENTER_SMOOTHING", "0.74"))
TARGET_CENTER_SMOOTHING_NEAR = float(os.getenv("TARGET_CENTER_SMOOTHING_NEAR", "0.52"))
TARGET_CENTER_SMOOTHING_FAR = float(os.getenv("TARGET_CENTER_SMOOTHING_FAR", "0.88"))
TARGET_CENTER_SMOOTHING_FAR_PX = float(os.getenv("TARGET_CENTER_SMOOTHING_FAR_PX", "280"))
TARGET_MAX_CENTER_STEP_PX = float(os.getenv("TARGET_MAX_CENTER_STEP_PX", "260"))
TARGET_MOTOR_MAX_STEP_PX = float(os.getenv("TARGET_MOTOR_MAX_STEP_PX", "170"))
TARGET_MOTOR_CENTER_DEAD_BAND_PX = float(os.getenv("TARGET_MOTOR_CENTER_DEAD_BAND_PX", "5"))
TRACK_SERVO_GAIN = float(os.getenv("TRACK_SERVO_GAIN", "1.00"))
TRACK_SERVO_INITIAL_STEP_PX = float(os.getenv("TRACK_SERVO_INITIAL_STEP_PX", "10000"))
TRACK_LEAD_FRAMES = float(os.getenv("TRACK_LEAD_FRAMES", "0.0"))
TRACK_LEAD_MAX_PX = float(os.getenv("TRACK_LEAD_MAX_PX", "80"))
TRACK_LEAD_MIN_CONF = float(os.getenv("TRACK_LEAD_MIN_CONF", "0.65"))
TRACK_LEAD_VELOCITY_ALPHA = float(os.getenv("TRACK_LEAD_VELOCITY_ALPHA", "0.55"))
TRACK_LEAD_RESET_JUMP_PX = float(os.getenv("TRACK_LEAD_RESET_JUMP_PX", "240"))
TRACK_MOTOR_JUMP_HOLD_PX = float(os.getenv("TRACK_MOTOR_JUMP_HOLD_PX", "360"))
TRACK_MOTOR_JUMP_CONFIRM_PX = float(os.getenv("TRACK_MOTOR_JUMP_CONFIRM_PX", "140"))
TRACK_HOLD_MOTOR_ON_LOST = os.getenv("TRACK_HOLD_MOTOR_ON_LOST", "0") == "1"
TRACK_LOST_HOLD_PERIOD_SEC = float(os.getenv("TRACK_LOST_HOLD_PERIOD_SEC", "0.25"))
DISTANCE_MODEL_PATH = os.getenv(
    "DISTANCE_MODEL_PATH",
    os.path.join(MODELS_DIR, "laser_distance_calibration.json"),
)
DISTANCE_ESTIMATE_FEATURE = os.getenv("DISTANCE_ESTIMATE_FEATURE", "bbox_w")
DISTANCE_DEFAULT_MM = int(os.getenv("DISTANCE_DEFAULT_MM", "3000"))
DISTANCE_MIN_MM = int(os.getenv("DISTANCE_MIN_MM", "500"))
DISTANCE_MAX_MM = int(os.getenv("DISTANCE_MAX_MM", "8000"))
LASER_BBOX_TICK_MODEL_PATH = os.getenv(
    "LASER_BBOX_TICK_MODEL_PATH",
    os.path.join(MODELS_DIR, "laser_bbox_tick_calibration.json"),
)
LASER_RUNTIME_CALIBRATION = os.getenv("LASER_RUNTIME_CALIBRATION", "0") == "1"
LASER_RUNTIME_CAL_STEP = int(os.getenv("LASER_RUNTIME_CAL_STEP", "4"))
LASER_RUNTIME_CAL_BIG_STEP = int(os.getenv("LASER_RUNTIME_CAL_BIG_STEP", "40"))
ULTRA_CHAN_LASER_ENABLE = os.getenv("ULTRA_CHAN_LASER_ENABLE", "1") == "1"
ULTRA_CHAN_LASER_ID = int(os.getenv("ULTRA_CHAN_LASER_ID", "3"))
ULTRA_CHAN_LASER_CENTER = int(os.getenv("ULTRA_CHAN_LASER_CENTER", "2048"))
ULTRA_CHAN_CAMERA_LASER_OFFSET_MM = int(os.getenv("ULTRA_CHAN_CAMERA_LASER_OFFSET_MM", "37"))
ULTRA_CHAN_LASER_SIGN = int(os.getenv("ULTRA_CHAN_LASER_SIGN", "1"))
LASER_PIN_MODE = os.getenv("LASER_PIN_MODE", "BOARD").upper()
LASER_PIN = int(os.getenv("LASER_PIN", "7"))
LASER_ACTIVE_HIGH = os.getenv("LASER_ACTIVE_HIGH", "1") == "1"
LASER_ENABLED = os.getenv("LASER_ENABLED", "1") == "1"
LASER_ALWAYS_ON = os.getenv("LASER_ALWAYS_ON", "0") == "1"
LASER_AUTO_ON_TARGET = os.getenv("LASER_AUTO_ON_TARGET", "1") == "1"
LASER_LOST_GRACE_SEC = float(os.getenv("LASER_LOST_GRACE_SEC", "0.08"))
LASER_PATTERN_ON_SPACE = os.getenv("LASER_PATTERN_ON_SPACE", "1") == "1"
LASER_PATTERN_BITS = os.getenv("LASER_PATTERN_BITS", "110111")
LASER_PATTERN_UNIT_SEC = float(os.getenv("LASER_PATTERN_UNIT_SEC", "0.12"))
LASER_PATTERN_GAP_SEC = float(os.getenv("LASER_PATTERN_GAP_SEC", "0.04"))
LASER_SPOT_ENABLED = os.getenv("LASER_SPOT_ENABLED", "1") == "1"
LASER_SPOT_COLOR = os.getenv("LASER_SPOT_COLOR", "red").strip().lower()
LASER_SPOT_ROI_MARGIN_RATIO = float(os.getenv("LASER_SPOT_ROI_MARGIN_RATIO", "0.20"))
LASER_SPOT_ROI_MARGIN_PX = int(os.getenv("LASER_SPOT_ROI_MARGIN_PX", "24"))
LASER_SPOT_MIN_AREA = int(os.getenv("LASER_SPOT_MIN_AREA", "1"))
LASER_SPOT_MAX_AREA = int(os.getenv("LASER_SPOT_MAX_AREA", "180"))
LASER_SPOT_MIN_VALUE = int(os.getenv("LASER_SPOT_MIN_VALUE", "145"))
LASER_SPOT_DIFF_MIN_VALUE = int(os.getenv("LASER_SPOT_DIFF_MIN_VALUE", "50"))
LASER_SPOT_MIN_SAT = int(os.getenv("LASER_SPOT_MIN_SAT", "70"))
LASER_SPOT_RED_DOMINANCE = int(os.getenv("LASER_SPOT_RED_DOMINANCE", "28"))
LASER_SPOT_HIT_WINDOW = int(os.getenv("LASER_SPOT_HIT_WINDOW", "5"))
LASER_SPOT_HIT_MIN_FRAMES = int(os.getenv("LASER_SPOT_HIT_MIN_FRAMES", "3"))
LASER_SPOT_HIT_INNER_RATIO = float(os.getenv("LASER_SPOT_HIT_INNER_RATIO", "1.0"))
LASER_SPOT_HIT_MARGIN_PX = int(os.getenv("LASER_SPOT_HIT_MARGIN_PX", "0"))
LASER_SPOT_CLOSED_LOOP = os.getenv("LASER_SPOT_CLOSED_LOOP", "0") == "1"
LASER_SPOT_CLOSED_LOOP_SIGN = int(os.getenv("LASER_SPOT_CLOSED_LOOP_SIGN", "1"))
LASER_SPOT_EDGE_MARGIN_PX = int(os.getenv("LASER_SPOT_EDGE_MARGIN_PX", "8"))
LASER_SPOT_TICK_STEP = int(os.getenv("LASER_SPOT_TICK_STEP", "2"))
LASER_SPOT_TICK_BIG_STEP = int(os.getenv("LASER_SPOT_TICK_BIG_STEP", "6"))
LASER_SPOT_BIG_ERROR_PX = int(os.getenv("LASER_SPOT_BIG_ERROR_PX", "30"))
LASER_SPOT_CORRECTION_LIMIT_TICK = int(os.getenv("LASER_SPOT_CORRECTION_LIMIT_TICK", "120"))
LASER_SPOT_CORRECTION_PERIOD_SEC = float(os.getenv("LASER_SPOT_CORRECTION_PERIOD_SEC", "0.08"))
FIRE_ASSESS_WINDOW_SEC = float(os.getenv("FIRE_ASSESS_WINDOW_SEC", "1.0"))
FIRE_HIT_MIN_FRAMES = int(os.getenv("FIRE_HIT_MIN_FRAMES", "1"))
FIRE_HIT_PULSE_SEC = float(os.getenv("FIRE_HIT_PULSE_SEC", "0.35"))
FIRE_RESULT_DISPLAY_SEC = float(os.getenv("FIRE_RESULT_DISPLAY_SEC", "1.0"))
LASER_BBOX_DIRECT_AIM = os.getenv("LASER_BBOX_DIRECT_AIM", "1") == "1"
LASER_BBOX_AIM_UPDATE_PERIOD_SEC = float(os.getenv("LASER_BBOX_AIM_UPDATE_PERIOD_SEC", "0.06"))
LASER_BBOX_AIM_MIN_DELTA_TICK = int(os.getenv("LASER_BBOX_AIM_MIN_DELTA_TICK", "2"))
LASER_BBOX_AIM_OFFSET_TICK = int(os.getenv("LASER_BBOX_AIM_OFFSET_TICK", "0"))
LASER_CAMERA_CENTER_LOCK = os.getenv("LASER_CAMERA_CENTER_LOCK", "0") == "1"
LASER_CAMERA_CENTER_TICK = int(os.getenv("LASER_CAMERA_CENTER_TICK", "1965"))
LASER_CAMERA_CENTER_RANGE_COMP = os.getenv("LASER_CAMERA_CENTER_RANGE_COMP", "1") == "1"
LASER_CAMERA_CENTER_RANGE_COMP_USE_DISTANCE = os.getenv("LASER_CAMERA_CENTER_RANGE_COMP_USE_DISTANCE", "1") == "1"
LASER_CAMERA_CENTER_NEAR_DISTANCE_MM = int(os.getenv("LASER_CAMERA_CENTER_NEAR_DISTANCE_MM", "1000"))
LASER_CAMERA_CENTER_FAR_DISTANCE_MM = int(os.getenv("LASER_CAMERA_CENTER_FAR_DISTANCE_MM", "3000"))
LASER_CAMERA_CENTER_NEAR_BBOX_H = float(os.getenv("LASER_CAMERA_CENTER_NEAR_BBOX_H", "64"))
LASER_CAMERA_CENTER_FAR_BBOX_H = float(os.getenv("LASER_CAMERA_CENTER_FAR_BBOX_H", "19"))
LASER_CAMERA_CENTER_FAR_OFFSET_TICK = int(os.getenv("LASER_CAMERA_CENTER_FAR_OFFSET_TICK", "36"))
ULTRA_CHAN_LASER_VERTICAL_FOV_DEG = float(os.getenv("ULTRA_CHAN_LASER_VERTICAL_FOV_DEG", os.getenv("ULTRA_YUBIN_LASER_VERTICAL_FOV_DEG", "43")))

# Ultra96 bridge. Keep ULTRA_CHAN aliases because this v1 branch imports
# Chani's tracking/laser tuning, while still accepting ULTRA_YUBIN names.
ULTRA_CHAN_HOST = os.getenv("ULTRA_CHAN_HOST", os.getenv("ULTRA_YUBIN_HOST", "192.168.3.1"))
ULTRA_CHAN_PORT = int(os.getenv("ULTRA_CHAN_PORT", os.getenv("ULTRA_YUBIN_PORT", "5016")))
ULTRA_CHAN_TIMEOUT_SEC = float(os.getenv("ULTRA_CHAN_TIMEOUT_SEC", os.getenv("ULTRA_YUBIN_TIMEOUT_SEC", "0.08")))
ULTRA_CHAN_CONTROL_PERIOD_SEC = float(os.getenv("ULTRA_CHAN_CONTROL_PERIOD_SEC", os.getenv("ULTRA_YUBIN_CONTROL_PERIOD_SEC", "0.020")))
ULTRA_CHAN_DEADBAND_PX = int(os.getenv("ULTRA_CHAN_DEADBAND_PX", os.getenv("ULTRA_YUBIN_DEADBAND_PX", "6")))
ULTRA_CHAN_DEADBAND_X_PX = int(os.getenv("ULTRA_CHAN_DEADBAND_X_PX", os.getenv("ULTRA_YUBIN_DEADBAND_X_PX", str(ULTRA_CHAN_DEADBAND_PX))))
ULTRA_CHAN_DEADBAND_Y_PX = int(os.getenv("ULTRA_CHAN_DEADBAND_Y_PX", os.getenv("ULTRA_YUBIN_DEADBAND_Y_PX", str(ULTRA_CHAN_DEADBAND_PX))))
ULTRA_CHAN_SMOOTH_ALPHA = float(os.getenv("ULTRA_CHAN_SMOOTH_ALPHA", os.getenv("ULTRA_YUBIN_SMOOTH_ALPHA", "0.76")))
ULTRA_CHAN_SMOOTH_ALPHA_X = float(os.getenv("ULTRA_CHAN_SMOOTH_ALPHA_X", os.getenv("ULTRA_YUBIN_SMOOTH_ALPHA_X", str(ULTRA_CHAN_SMOOTH_ALPHA))))
ULTRA_CHAN_SMOOTH_ALPHA_Y = float(os.getenv("ULTRA_CHAN_SMOOTH_ALPHA_Y", os.getenv("ULTRA_YUBIN_SMOOTH_ALPHA_Y", str(ULTRA_CHAN_SMOOTH_ALPHA))))
ULTRA_YUBIN_HOST = ULTRA_CHAN_HOST
ULTRA_YUBIN_PORT = ULTRA_CHAN_PORT
ULTRA_YUBIN_TIMEOUT_SEC = ULTRA_CHAN_TIMEOUT_SEC
ULTRA_CHAN_ASYNC_SEND = os.getenv("ULTRA_CHAN_ASYNC_SEND", os.getenv("ULTRA_YUBIN_ASYNC_SEND", "1")) == "1"
ULTRA_CHAN_CENTER_ON_START = os.getenv("ULTRA_CHAN_CENTER_ON_START", os.getenv("ULTRA_YUBIN_CENTER_ON_START", "1")) == "1"

# Jetson -> Raspberry Pi dashboard UDP telemetry.
JETSON_SENDER_ENABLED = os.getenv("JETSON_SENDER_ENABLED", "1") == "1"
JETSON_SENDER_HOST = os.getenv(
    "JETSON_SENDER_HOST",
    os.getenv("PI_IP", os.getenv("RASPBERRY_PI_IP", "192.168.0.7")),
)
JETSON_SENDER_PORT = int(os.getenv("JETSON_SENDER_PORT", os.getenv("PI_PORT", "5005")))
JETSON_SENDER_RATE_HZ = float(os.getenv("JETSON_SENDER_RATE_HZ", "20"))

# Motor display limits.
PAN_MIN = int(os.getenv("PAN_MIN", "0"))
PAN_MAX = int(os.getenv("PAN_MAX", "4095"))
TILT_MIN = int(os.getenv("TILT_MIN", "2340"))
TILT_MAX = int(os.getenv("TILT_MAX", "3048"))
PAN_DIR = int(os.getenv("PAN_DIR", "1"))
TILT_DIR = int(os.getenv("TILT_DIR", "1"))

# Tello audio fallback. When enabled, this is used only while YOLO has no target.
TELLO_AUDIO_FALLBACK = os.getenv("TELLO_AUDIO_FALLBACK", "0") == "1"
TELLO_AUDIO_MODE = os.getenv("TELLO_AUDIO_MODE", "model").lower()
TELLO_AUDIO_CONFIG = os.getenv("TELLO_AUDIO_CONFIG", os.path.join(AUDIO_MODEL_DIR, "config.json"))
TELLO_AUDIO_TFLITE = os.getenv(
    "TELLO_AUDIO_TFLITE",
    os.path.join(AUDIO_MODEL_DIR, "tello_detector_cnn_retrained_jetson.tflite"),
)
TELLO_AUDIO_KERAS = os.path.join(MODELS_DIR, "tello_detector.keras")
TELLO_AUDIO_JUNMO_ROOT = os.getenv("TELLO_AUDIO_JUNMO_ROOT", ROOT)
TELLO_AUDIO_JUNMO_CONFIG = os.getenv("TELLO_AUDIO_JUNMO_CONFIG", TELLO_AUDIO_CONFIG)
TELLO_AUDIO_JUNMO_MODEL = os.getenv("TELLO_AUDIO_JUNMO_MODEL", TELLO_AUDIO_TFLITE)
TELLO_AUDIO_THRESHOLD = float(os.getenv("TELLO_AUDIO_THRESHOLD", "0.50"))
TELLO_AUDIO_MIN_AVG_SCORE = float(os.getenv("TELLO_AUDIO_MIN_AVG_SCORE", "0.55"))
TELLO_AUDIO_CONSECUTIVE = int(os.getenv("TELLO_AUDIO_CONSECUTIVE", "2"))
TELLO_AUDIO_COOLDOWN_SEC = float(os.getenv("TELLO_AUDIO_COOLDOWN_SEC", "0.1"))
TELLO_AUDIO_MIN_RMS = float(os.getenv("TELLO_AUDIO_MIN_RMS", "0.003"))
TELLO_AUDIO_STRIDE_SEC = float(os.getenv("TELLO_AUDIO_STRIDE_SEC", "0.25"))
TELLO_AUDIO_PREPROCESS = os.getenv("TELLO_AUDIO_PREPROCESS", "1") == "1"
TELLO_AUDIO_BANDPASS_LOW = float(os.getenv("TELLO_AUDIO_BANDPASS_LOW", "1656.2"))
TELLO_AUDIO_BANDPASS_HIGH = float(os.getenv("TELLO_AUDIO_BANDPASS_HIGH", "2656.2"))
TELLO_AUDIO_BANDPASS_ORDER = int(os.getenv("TELLO_AUDIO_BANDPASS_ORDER", "5"))
TELLO_AUDIO_PRE_GAIN_NOISE_FLOOR = float(os.getenv("TELLO_AUDIO_PRE_GAIN_NOISE_FLOOR", "0.003"))
TELLO_AUDIO_PRE_GAIN_TARGET = float(os.getenv("TELLO_AUDIO_PRE_GAIN_TARGET", "0.9"))
TELLO_AUDIO_PREPROCESS_TARGET = os.getenv("TELLO_AUDIO_PREPROCESS_TARGET", "doa").lower()
TELLO_AUDIO_ALSA_DEVICE = os.getenv("TELLO_AUDIO_ALSA_DEVICE", "auto")
TELLO_AUDIO_CHANNELS = int(os.getenv("TELLO_AUDIO_CHANNELS", "6"))
TELLO_AUDIO_DOA_OFFSET = int(os.getenv("TELLO_AUDIO_DOA_OFFSET", "0"))
TELLO_AUDIO_MOTOR_ZERO_DOA_DEG = float(os.getenv("TELLO_AUDIO_MOTOR_ZERO_DOA_DEG", "90"))
TELLO_AUDIO_DOA_SIGN = int(os.getenv("TELLO_AUDIO_DOA_SIGN", "1"))
TELLO_AUDIO_DOA_METHOD = os.getenv("TELLO_AUDIO_DOA_METHOD", "auto")
TELLO_AUDIO_DIRECTION_MODE = os.getenv("TELLO_AUDIO_DIRECTION_MODE", "legacy").lower()
TELLO_AUDIO_DIRECTION_MODEL = os.getenv(
    "TELLO_AUDIO_DIRECTION_MODEL",
    os.path.join(MODELS_DIR, "audio_direction", "direction_6sector_lr.npz"),
)
TELLO_AUDIO_GCC_CAL_OFFSET_DEG = float(os.getenv("TELLO_AUDIO_GCC_CAL_OFFSET_DEG", "120"))
TELLO_AUDIO_DIRECTION_SECTOR_DEG = float(os.getenv("TELLO_AUDIO_DIRECTION_SECTOR_DEG", "60"))
TELLO_AUDIO_BACKEND = os.getenv("TELLO_AUDIO_BACKEND", "arecord")
TELLO_AUDIO_ALLOW_USB_RESET = os.getenv("TELLO_AUDIO_ALLOW_USB_RESET", "0") == "1"
TELLO_AUDIO_MIC_DISTANCE = float(os.getenv("TELLO_AUDIO_MIC_DISTANCE", "0.045"))
TELLO_AUDIO_MAX_AGE_SEC = float(os.getenv("TELLO_AUDIO_MAX_AGE_SEC", "1.5"))
TELLO_AUDIO_LAZY_START = os.getenv("TELLO_AUDIO_LAZY_START", "0") == "1"
TELLO_AUDIO_LAZY_START_AFTER_SEC = float(os.getenv("TELLO_AUDIO_LAZY_START_AFTER_SEC", "0.8"))
TELLO_AUDIO_PAUSE_WHILE_VISION = os.getenv("TELLO_AUDIO_PAUSE_WHILE_VISION", "1") == "1"
TELLO_AUDIO_VERBOSE = os.getenv("TELLO_AUDIO_VERBOSE", "0") == "1"
TELLO_AUDIO_CONTROL_PERIOD_SEC = float(os.getenv("TELLO_AUDIO_CONTROL_PERIOD_SEC", "0.10"))
TELLO_AUDIO_KEEPALIVE_SEC = float(os.getenv("TELLO_AUDIO_KEEPALIVE_SEC", "0.25"))
TELLO_AUDIO_MIN_CHANGE_DEG = float(os.getenv("TELLO_AUDIO_MIN_CHANGE_DEG", "0"))
TELLO_AUDIO_CLAMP_DEG = float(os.getenv("TELLO_AUDIO_CLAMP_DEG", "180"))
TELLO_AUDIO_ALWAYS_SEND = os.getenv("TELLO_AUDIO_ALWAYS_SEND", "1") == "1"
TELLO_AUDIO_MOTOR_NOISE_BLIND_SEC = float(os.getenv("TELLO_AUDIO_MOTOR_NOISE_BLIND_SEC", "0.8"))
TELLO_AUDIO_VISION_HOLD_SEC = float(os.getenv("TELLO_AUDIO_VISION_HOLD_SEC", "0.15"))
TELLO_AUDIO_DOA_ONLY_SEARCH = os.getenv("TELLO_AUDIO_DOA_ONLY_SEARCH", "0") == "1"
TELLO_AUDIO_DIRECTION_BIN_DEG = float(os.getenv("TELLO_AUDIO_DIRECTION_BIN_DEG", "15"))
TELLO_AUDIO_DIRECTION_COOLDOWN_SEC = float(os.getenv("TELLO_AUDIO_DIRECTION_COOLDOWN_SEC", "0.5"))
TELLO_AUDIO_MAX_SEARCH_ATTEMPTS = int(os.getenv("TELLO_AUDIO_MAX_SEARCH_ATTEMPTS", "0"))
TELLO_AUDIO_ATTEMPT_RESET_SEC = float(os.getenv("TELLO_AUDIO_ATTEMPT_RESET_SEC", "5.0"))
TELLO_AUDIO_STABLE_WINDOW = int(os.getenv("TELLO_AUDIO_STABLE_WINDOW", "3"))
TELLO_AUDIO_STABLE_MIN_VOTES = int(os.getenv("TELLO_AUDIO_STABLE_MIN_VOTES", "2"))
TELLO_AUDIO_STABLE_MAX_SPREAD_DEG = float(os.getenv("TELLO_AUDIO_STABLE_MAX_SPREAD_DEG", "80"))
TELLO_AUDIO_MAX_JUMP_DEG = float(os.getenv("TELLO_AUDIO_MAX_JUMP_DEG", "0"))
TELLO_AUDIO_REJECT_REAR = os.getenv("TELLO_AUDIO_REJECT_REAR", "0") == "1"

# UI-only compatibility with the CRANE display module. Ultra96/FPGA pan-tilt
# control remains in src/control/ultra_yubin_motor.py.
LASER_SERVO_MANUAL_STEP_DEG = float(os.getenv("LASER_SERVO_MANUAL_STEP_DEG", "1.0"))
