#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "${ROOT}"

# Vision fast profile + ReSpeaker drone-audio fallback.
export ULTRA_YUBIN_V1_TRACK_DIRECT_PS=1
export ULTRA_YUBIN_V1_TRACK_PL_SHADOW=0
export ULTRA_YUBIN_V1_RESTART=1
export ULTRA_CHAN_ASYNC_SEND="${ULTRA_CHAN_ASYNC_SEND:-1}"
export ULTRA_YUBIN_V1_PROFILE_ACCEL="${ULTRA_YUBIN_V1_PROFILE_ACCEL:-120}"
export ULTRA_YUBIN_V1_PROFILE_VELOCITY="${ULTRA_YUBIN_V1_PROFILE_VELOCITY:-280}"
export ULTRA_YUBIN_V1_TRACK_PAN_LIMIT="${ULTRA_YUBIN_V1_TRACK_PAN_LIMIT:-2047}"
export ULTRA_YUBIN_V1_TRACK_TILT_LIMIT="${ULTRA_YUBIN_V1_TRACK_TILT_LIMIT:-360}"

export YOLO_CONF="${YOLO_CONF:-0.35}"
export YOLO_FAST_DETECT="${YOLO_FAST_DETECT:-0}"
export TRACK_TARGET_MIN_CONF="${TRACK_TARGET_MIN_CONF:-0.50}"
export TRACK_MOTOR_MIN_CONF="${TRACK_MOTOR_MIN_CONF:-0.50}"
export TRACK_REACQUIRE_MIN_CONF="${TRACK_REACQUIRE_MIN_CONF:-0.60}"
export TRACK_WEAK_REACQUIRE_CONF="${TRACK_WEAK_REACQUIRE_CONF:-0.45}"
export TRACK_WEAK_REACQUIRE_AREA="${TRACK_WEAK_REACQUIRE_AREA:-50}"
export TRACK_REACQUIRE_AFTER_ABSENT_FRAMES="${TRACK_REACQUIRE_AFTER_ABSENT_FRAMES:-3}"
export TRACK_STICKY_MAX_DIST_PX="${TRACK_STICKY_MAX_DIST_PX:-10000}"
export TRACK_HOLD_LAST_FRAMES="${TRACK_HOLD_LAST_FRAMES:-12}"
export TRACK_HOLD_PREDICT_MAX_STEP_PX="${TRACK_HOLD_PREDICT_MAX_STEP_PX:-18}"
export TRACK_MOTOR_USE_HELD="${TRACK_MOTOR_USE_HELD:-1}"

export ULTRA_CHAN_CONTROL_PERIOD_SEC="${ULTRA_CHAN_CONTROL_PERIOD_SEC:-0.010}"
export ULTRA_CHAN_SMOOTH_ALPHA_X="${ULTRA_CHAN_SMOOTH_ALPHA_X:-0.98}"
export ULTRA_CHAN_SMOOTH_ALPHA_Y="${ULTRA_CHAN_SMOOTH_ALPHA_Y:-0.95}"
export TARGET_CENTER_SMOOTHING_NEAR="${TARGET_CENTER_SMOOTHING_NEAR:-0.92}"
export TARGET_CENTER_SMOOTHING_FAR="${TARGET_CENTER_SMOOTHING_FAR:-0.99}"
export TARGET_MOTOR_MAX_STEP_PX="${TARGET_MOTOR_MAX_STEP_PX:-600}"
export TARGET_MAX_CENTER_STEP_PX="${TARGET_MAX_CENTER_STEP_PX:-600}"
export TARGET_MOTOR_CENTER_DEAD_BAND_PX="${TARGET_MOTOR_CENTER_DEAD_BAND_PX:-1}"
export TRACK_CENTER_LOCK_X_PX="${TRACK_CENTER_LOCK_X_PX:-5}"
export TRACK_CENTER_LOCK_Y_PX="${TRACK_CENTER_LOCK_Y_PX:-5}"
export TRACK_HOLD_MOTOR_ON_LOST="${TRACK_HOLD_MOTOR_ON_LOST:-1}"

export CAMERA_APPLY_SETTINGS="${CAMERA_APPLY_SETTINGS:-0}"
export CAMERA_AUTO_EXPOSURE="${CAMERA_AUTO_EXPOSURE:-1}"
export CAMERA_EXPOSURE="${CAMERA_EXPOSURE:-43}"
export CAMERA_GAIN="${CAMERA_GAIN:-16}"
export CAMERA_BRIGHTNESS="${CAMERA_BRIGHTNESS:-0}"
export CAMERA_CONTRAST="${CAMERA_CONTRAST:-0}"
export CAMERA_SATURATION="${CAMERA_SATURATION:-64}"
export CAMERA_SHARPNESS="${CAMERA_SHARPNESS:-2}"
export CAMERA_BACKLIGHT="${CAMERA_BACKLIGHT:-0}"

export TELLO_AUDIO_FALLBACK=1
export TELLO_AUDIO_MODE="${TELLO_AUDIO_MODE:-junmo}"
export TELLO_AUDIO_JUNMO_MODEL="${TELLO_AUDIO_JUNMO_MODEL:-/home/jetson/junmoyolo26/tello_detector.tflite}"
export TELLO_AUDIO_THRESHOLD="${TELLO_AUDIO_THRESHOLD:-0.70}"
export TELLO_AUDIO_CONSECUTIVE="${TELLO_AUDIO_CONSECUTIVE:-1}"
export TELLO_AUDIO_LAZY_START="${TELLO_AUDIO_LAZY_START:-1}"
export TELLO_AUDIO_LAZY_START_AFTER_SEC="${TELLO_AUDIO_LAZY_START_AFTER_SEC:-0.8}"
export TELLO_AUDIO_VERBOSE="${TELLO_AUDIO_VERBOSE:-0}"
export TELLO_AUDIO_USB_RESET_ON_ERROR="${TELLO_AUDIO_USB_RESET_ON_ERROR:-1}"
export TELLO_AUDIO_MOTOR_ZERO_DOA_DEG="${TELLO_AUDIO_MOTOR_ZERO_DOA_DEG:-90}"
export TELLO_AUDIO_DOA_SIGN="${TELLO_AUDIO_DOA_SIGN:-1}"
export TELLO_AUDIO_STABLE_WINDOW="${TELLO_AUDIO_STABLE_WINDOW:-3}"
export TELLO_AUDIO_STABLE_MIN_VOTES="${TELLO_AUDIO_STABLE_MIN_VOTES:-1}"
export TELLO_AUDIO_CONTROL_PERIOD_SEC="${TELLO_AUDIO_CONTROL_PERIOD_SEC:-0.35}"
export TELLO_AUDIO_KEEPALIVE_SEC="${TELLO_AUDIO_KEEPALIVE_SEC:-1.0}"
export TELLO_AUDIO_MIN_CHANGE_DEG="${TELLO_AUDIO_MIN_CHANGE_DEG:-12}"
export TELLO_AUDIO_CLAMP_DEG="${TELLO_AUDIO_CLAMP_DEG:-180}"
export TELLO_AUDIO_VISION_HOLD_SEC="${TELLO_AUDIO_VISION_HOLD_SEC:-0.15}"
export TELLO_AUDIO_DIRECTION_BIN_DEG="${TELLO_AUDIO_DIRECTION_BIN_DEG:-15}"
export TELLO_AUDIO_DIRECTION_COOLDOWN_SEC="${TELLO_AUDIO_DIRECTION_COOLDOWN_SEC:-1.0}"
export TELLO_AUDIO_MAX_SEARCH_ATTEMPTS="${TELLO_AUDIO_MAX_SEARCH_ATTEMPTS:-0}"
export TELLO_AUDIO_ATTEMPT_RESET_SEC="${TELLO_AUDIO_ATTEMPT_RESET_SEC:-5.0}"
export TELLO_AUDIO_DOA_ONLY_SEARCH="${TELLO_AUDIO_DOA_ONLY_SEARCH:-0}"

echo "[run_demo_ps_fast2_audio] detect YOLO_CONF=${YOLO_CONF} fast_detect=${YOLO_FAST_DETECT} async_motor=${ULTRA_CHAN_ASYNC_SEND} target_min=${TRACK_TARGET_MIN_CONF} motor_min=${TRACK_MOTOR_MIN_CONF} reacquire=${TRACK_REACQUIRE_MIN_CONF}/${TRACK_WEAK_REACQUIRE_CONF} sticky=${TRACK_STICKY_MAX_DIST_PX} hold_frames=${TRACK_HOLD_LAST_FRAMES} audio=${TELLO_AUDIO_MODE} audio_lazy=${TELLO_AUDIO_LAZY_START}"

./tools/deploy_ultra96_ps_usb.sh
exec ./run_demo.sh --audio-fallback "$@"
