#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "${ROOT}"

# Field-audio profile for large/noisy rooms. This keeps the normal PL-drive
# vision path, but relaxes only the Tello ReSpeaker fallback gates.
export TELLO_AUDIO_THRESHOLD="${TELLO_AUDIO_THRESHOLD:-0.65}"
export TELLO_AUDIO_MIN_AVG_SCORE="${TELLO_AUDIO_MIN_AVG_SCORE:-0.65}"
export TELLO_AUDIO_CONSECUTIVE="${TELLO_AUDIO_CONSECUTIVE:-1}"
export TELLO_AUDIO_STABLE_WINDOW="${TELLO_AUDIO_STABLE_WINDOW:-3}"
export TELLO_AUDIO_STABLE_MIN_VOTES="${TELLO_AUDIO_STABLE_MIN_VOTES:-1}"
export TELLO_AUDIO_STABLE_MAX_SPREAD_DEG="${TELLO_AUDIO_STABLE_MAX_SPREAD_DEG:-45}"
export TELLO_AUDIO_MIN_CHANGE_DEG="${TELLO_AUDIO_MIN_CHANGE_DEG:-5}"
export TELLO_AUDIO_DIRECTION_COOLDOWN_SEC="${TELLO_AUDIO_DIRECTION_COOLDOWN_SEC:-0.4}"
export TELLO_AUDIO_CONTROL_PERIOD_SEC="${TELLO_AUDIO_CONTROL_PERIOD_SEC:-0.25}"
export TELLO_AUDIO_KEEPALIVE_SEC="${TELLO_AUDIO_KEEPALIVE_SEC:-0.5}"
export TELLO_AUDIO_LAZY_START_AFTER_SEC="${TELLO_AUDIO_LAZY_START_AFTER_SEC:-0.2}"
export TELLO_AUDIO_VERBOSE="${TELLO_AUDIO_VERBOSE:-1}"

echo "[run_demo_pl_drive_audio_hot] threshold=${TELLO_AUDIO_THRESHOLD} min_avg=${TELLO_AUDIO_MIN_AVG_SCORE} consecutive=${TELLO_AUDIO_CONSECUTIVE} stable=${TELLO_AUDIO_STABLE_WINDOW}/${TELLO_AUDIO_STABLE_MIN_VOTES}"
exec ./run_demo_pl_drive.sh "$@"
