#!/usr/bin/env bash
TELLO_AUDIO_FALLBACK=1 TELLO_AUDIO_MODE="${TELLO_AUDIO_MODE:-doa}" TELLO_AUDIO_ALSA_DEVICE="${TELLO_AUDIO_ALSA_DEVICE:-auto}" TELLO_AUDIO_CONTROL_PERIOD_SEC="${TELLO_AUDIO_CONTROL_PERIOD_SEC:-0.35}" TELLO_AUDIO_MIN_CHANGE_DEG="${TELLO_AUDIO_MIN_CHANGE_DEG:-12}" TELLO_AUDIO_CLAMP_DEG="${TELLO_AUDIO_CLAMP_DEG:-45}" ./run_demo_crop.sh --audio-fallback "$@"
