#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "${ROOT}"

# Comparison profile: motors are still driven by PS direct, but the bridge also
# runs the PL controller on the same target and prints pl_diff_* in replies.
export ULTRA_YUBIN_V1_TRACK_DIRECT_PS=1
export ULTRA_YUBIN_V1_TRACK_PL_SHADOW=1
export ULTRA_YUBIN_V1_RESTART=1
export ULTRA_CHAN_ASYNC_SEND="${ULTRA_CHAN_ASYNC_SEND:-1}"
export ULTRA_YUBIN_V1_PROFILE_ACCEL="${ULTRA_YUBIN_V1_PROFILE_ACCEL:-150}"
export ULTRA_YUBIN_V1_PROFILE_VELOCITY="${ULTRA_YUBIN_V1_PROFILE_VELOCITY:-340}"
export ULTRA_YUBIN_V1_TRACK_TILT_LIMIT="${ULTRA_YUBIN_V1_TRACK_TILT_LIMIT:-360}"

export YOLO_CONF="${YOLO_CONF:-0.35}"
export YOLO_FAST_DETECT="${YOLO_FAST_DETECT:-1}"
export TRACK_TARGET_MIN_CONF="${TRACK_TARGET_MIN_CONF:-0.50}"
export TRACK_MOTOR_MIN_CONF="${TRACK_MOTOR_MIN_CONF:-0.50}"
export TRACK_REACQUIRE_MIN_CONF="${TRACK_REACQUIRE_MIN_CONF:-0.60}"
export TRACK_WEAK_REACQUIRE_CONF="${TRACK_WEAK_REACQUIRE_CONF:-0.45}"
export TRACK_WEAK_REACQUIRE_AREA="${TRACK_WEAK_REACQUIRE_AREA:-50}"
export TRACK_REACQUIRE_AFTER_ABSENT_FRAMES="${TRACK_REACQUIRE_AFTER_ABSENT_FRAMES:-3}"
export TRACK_STICKY_MAX_DIST_PX="${TRACK_STICKY_MAX_DIST_PX:-10000}"
export TRACK_HOLD_LAST_FRAMES="${TRACK_HOLD_LAST_FRAMES:-5}"
export TRACK_HOLD_PREDICT_MAX_STEP_PX="${TRACK_HOLD_PREDICT_MAX_STEP_PX:-10}"
export TRACK_MOTOR_USE_HELD="${TRACK_MOTOR_USE_HELD:-0}"

export ULTRA_CHAN_CONTROL_PERIOD_SEC="${ULTRA_CHAN_CONTROL_PERIOD_SEC:-0.008}"
export ULTRA_CHAN_DEADBAND_PX="${ULTRA_CHAN_DEADBAND_PX:-1}"
export ULTRA_CHAN_DEADBAND_X_PX="${ULTRA_CHAN_DEADBAND_X_PX:-1}"
export ULTRA_CHAN_DEADBAND_Y_PX="${ULTRA_CHAN_DEADBAND_Y_PX:-1}"
export ULTRA_CHAN_SMOOTH_ALPHA_X="${ULTRA_CHAN_SMOOTH_ALPHA_X:-1.00}"
export ULTRA_CHAN_SMOOTH_ALPHA_Y="${ULTRA_CHAN_SMOOTH_ALPHA_Y:-0.98}"
export TARGET_CENTER_SMOOTHING_NEAR="${TARGET_CENTER_SMOOTHING_NEAR:-0.98}"
export TARGET_CENTER_SMOOTHING_FAR="${TARGET_CENTER_SMOOTHING_FAR:-1.00}"
export TARGET_MOTOR_MAX_STEP_PX="${TARGET_MOTOR_MAX_STEP_PX:-800}"
export TARGET_MAX_CENTER_STEP_PX="${TARGET_MAX_CENTER_STEP_PX:-800}"
export TARGET_MOTOR_CENTER_DEAD_BAND_PX="${TARGET_MOTOR_CENTER_DEAD_BAND_PX:-0}"
export TRACK_CENTER_LOCK_X_PX="${TRACK_CENTER_LOCK_X_PX:-0}"
export TRACK_CENTER_LOCK_Y_PX="${TRACK_CENTER_LOCK_Y_PX:-0}"
export TRACK_HOLD_MOTOR_ON_LOST="${TRACK_HOLD_MOTOR_ON_LOST:-1}"

./tools/deploy_ultra96_ps_usb.sh
exec ./run_demo.sh "$@"
